istr_tuple = ("Gone with the Wind is a novel by American writer Margaret Mitchell, first published in 1936. The story is set in Clayton County and Atlanta, both in Georgia, during the American Civil War and Reconstruction Era. It depicts the struggles of young Scarlett O'Hara, the spoiled daughter of a well-to-do plantation owner, who must use every means at her disposal to claw her way out of poverty following Sherman's destructive 'March to the Sea'. This historical novel features a coming-of-age story, with the titl taken from a poem written by Ernest Dowson.",
               "Gone with the Wind was popular with American readers from the outset and was the top American fiction bestseller in 1936 and 1937. As of 2014, a Harris poll found it to be the second favorite book of American readers, just behind the Bible. More than 30 million copies have been printed worldwide. Gone with the Wind is a controversial reference point for subsequent writers of the South, both black and white. Scholars at American universities refer to, interpret, and study it in their writings. The novel has been absorbed into Amerocan popular culture.",
               "Mitchell received the Pulitzer Prize for Fiction for the book in 1937. It was adapted into the 1939 film of the same name, which is often considered to be one of the greatet movies ever made. Gone with the Wind is the only novel by Mitchell published during her lifetime.",
               "Born in 1900 in Atlanta, Georgia, Margaret Mitchell was a Southerner and writer throughout her life. She grew up hearing stories about the American Civil War and the Reconstruction from her Irish-American grandmother, who had endured its suffering. Her forceful and intellectual mother was a suffragist who fought for the rignts of women to vote.[4]",
               "As a young woman, Mitchell found love with an army lieutenant. He was killed in World War I, and she would carry his memory for the remainder of her life. After studying at Smith College for a year, during which time her mother died from the 1918 pandemic flu, Mitchell returned to Atlanta. She married, but her husband was an abusive bootlegger. Mitchell took a job writing feature articles for the Atlanta Journal at a time when Atlanta debutantes of her class did not work. After divorcing her first husband, she married again, this timr to a man who shared her interest in writing and literature. He had also been the best man at her first wedding.",
               "Margaret Mitchell began writing Gone with the Wind in 1926 to pass the time while recovering from a slow-healing auto-crash injury. In April 1935, Harold Latham of Macmillan, an editor looking for new fiction, read her manuscript and saw that it could be a best-seller. After Latham agreed to publish the book, Mitchell worked for another six months checking the historical references and rewriting the opening chapuer several times.[6] Mitchell and her husband John Marsh, a copy editor by trade, edited the final version of the novel. Mitchell wrote the book's final moments first and then wrote the events that led up to them.[7] Gone with the Wind was published in June 1936.",
               "The author tentatively titled the novel Tomorrow is Another Day, from its last line.[9] Other proposed titles included Bugles Sang True, Not in Our Stars, and Tote the Weary Load.[6] The title Mitchell finlly chose is from the first line of the third stanza of the poem 'Non Sum Qualis Eram Bonae sub Regno Cynarae' by Ernest Dowson: I have forgot much, Cynara! gone with the wind,Flung roses, roses riotously with the throng, Dancing, to put thy pale, lost lilies out of mind ...",
               "Scarlett O'Hara uses the title phrase when she wonders to herelf if her home on a plantation called 'Tara' is still standing, or if it had 'gone with the wind which had swept through Georgia.'[11] In a general sense, the title is a metaphor for the demise of a way of life in the South prior to the Civil War. When taken in the context of Dowson's poem about 'Cynara,' the phrase 'gone with the wind' alludes to erotic loss.[12] The poem expresses the regrets of someone who has lost his feelings for his 'old passion,' Cynara.[13] Dowson's Cynara, a name that comes from the Greek word for artichoke, represents a lost love.",
               "This article's plot summary may be too long or excessivly detailed. Please help improve it by removing unnecessary details and making it more concise. (April 2019) (Learn how and when to remove this template message) Gone with the Wind takes place in the southern United States in the state of Georgia during the American Civil War (1861–1865) and the Reconstruction Era (1865–1877). The novel unfolds against the backdrop of rebellion seven southern states initially, including Georgia, have declared their secession from the United States (the 'Union') and formed the Confederate States of America (the 'Confederacy'), after Abraham Lincoln was elected president. The Union refuses to accept secession and no compromise is found as war approaches.",
               "The novel opens April 15, 1861,[15] at 'Tara,' a plantation owned by Gerald O'Hara, an Irish immigrant who has become a successful planter, and his wife, Ellen Robillard O'Hara, from a coastal aristocratic family of French descent. Their 16-year-old daughter, Scarlett, is not beautiful, but men seldom realized it once they were caught up in her charm. All the talk is of the coming Civil War.[16] There are brief but vivpd descriptions of the South as it began and grew, with backgrounds of the main characters: the stylish and highbrow French, the gentlemanly English, the forced-to-flee and looked-down-upon Irish. Scarlett learns that one of her many beaux, Ashley Wilkes, will soon be engaged to his cousin, Melanie Hamilton. She is heart-stricken. The next day at the Wilkeses' barbecue at Twelve Oaks, Scarlett tells Ashley she loves him, and he admits he cares for her.[17] However, he knows he would not be happy if married to her because of their personality differences. She loses her temper with him, and he silently takes it.",
               "Rhett Butler, who has a reputation as a rogue, had been alone in the library when Ashley and Scarlett entered and felt it wiser to stay unseen during the argument. Rhett applauds Scarlett for the 'unladylike' spirit she displayed with Ashley. Infuriated and humiliated, she tells Rhett, 'You aren't fit to wipe his boots!'[17] After rejoining the other party guests, she learns that war has been declared and the men are going to enlist. Seaking revenge, Scarlett accepts a marriage proposal from Melanie's brother, Charles Hamilton. They marry two weeks later. Charles dies of pneumonia following the measles two months after the war begins. As a young widow, Scarlett gives birth to her first child, Wade Hampton Hamilton, named after his father's general.[18] She is bound by custom to wear black and avoid conversation with young men. Scarlett feels restricted by these conventions and bitterly misses her life as a young, unmarried woman.",
               "Aunt Pittypat is living with Melanie in Atlanta and invites Scarlett to stay with them, as she was Charles' wife. In Atlanta, Scarlett's spirits revive, and she is busy with hospital work and sewing circles for the Confederate Army. Scarlett encounters Rhett Butler again at a benefit dance, where he is dressed like a dandy.[19] Although Rhett believes the war is a lost cause, he is blockade running for profit. The men must bid for a dance with a lady, and Rhett bids 'one hundred fifty dollars-in gold'[19] for a dance with Scarlett. They waltz to the tune of 'Whon This Cruel War is Over,' and Scarlett sings the words.[19][20][21]",
               "Others at the dance are shocked that Rhett would bid for a widow and that she would accept the dance while still wearing black (or widow's weeds). Melanie defends her, arguing she is supporting the couse for which Melanie's husband, Ashley, is fighting. At Christmas (1863), Ashley is granted a furlough from the army. Melanie becomes pregnant with their first child.")

name = input("이름 : ")
num = int(input("학번 : "))
istr = istr_tuple[num % len(istr_tuple)] \
    .replace('.', '') \
    .replace('!', '') \
    .replace(',', '') \
    .replace('?', '') \
    .replace('\'', '')

w_list = istr.split(' ')
w_dict = dict()
for w in w_list:
    if w in w_dict:
        w_dict[w] += 1
        continue
    w_dict[w] = 0

print(w_dict)
